version: "3.9"

services:
  hospital-bulk:
    build: .
    container_name: hospital-bulk-service
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hospital_bulk.settings
